repos:
  - repo: https://github.com/gruntwork-io/pre-commit.git
    rev: v0.1.23
    hooks:
      - id: terragrunt-hclfmt
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: gofmt
      - id: golint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
#  - repo: https://github.com/terraform-docs/terraform-docs
#    rev: "v0.16.0" # e.g. "v0.11.2"
#    hooks:
#      - id: terraform-docs-go
#        args: ["ARGS", "TO PASS", "INCLUDING PATH"] # e.g. ["--output-file", "README.md", "./mymodule/path"]
